services:
  - type: web
    name: fridge-monitor
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fridge-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
